package model;
// Generated Mar 24, 2019 4:26:40 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaitietkiem generated by hbm2java
 */
@Entity
@Table(name = "loaitietkiem", catalog = "QLSTK")
public class Loaitietkiem implements java.io.Serializable {

	private String maLoaiTietKiem;
	private String thoiHan;
	private float laiSuat;
	private Set<Sotietkiem> sotietkiems = new HashSet<Sotietkiem>(0);

	public Loaitietkiem() {
	}

	public String toString() {
		return this.thoiHan;
	}
	
	public Loaitietkiem(String maLoaiTietKiem, String thoiHan, float laiSuat) {
		this.maLoaiTietKiem = maLoaiTietKiem;
		this.thoiHan = thoiHan;
		this.laiSuat = laiSuat;
	}

	public Loaitietkiem(String maLoaiTietKiem, String thoiHan, float laiSuat, Set<Sotietkiem> sotietkiems) {
		this.maLoaiTietKiem = maLoaiTietKiem;
		this.thoiHan = thoiHan;
		this.laiSuat = laiSuat;
		this.sotietkiems = sotietkiems;
	}

	@Id

	@Column(name = "MaLoaiTietKiem", unique = true, nullable = false, length = 20)
	public String getMaLoaiTietKiem() {
		return this.maLoaiTietKiem;
	}

	public void setMaLoaiTietKiem(String maLoaiTietKiem) {
		this.maLoaiTietKiem = maLoaiTietKiem;
	}

	@Column(name = "ThoiHan", nullable = false, length = 50)
	public String getThoiHan() {
		return this.thoiHan;
	}

	public void setThoiHan(String thoiHan) {
		this.thoiHan = thoiHan;
	}

	@Column(name = "LaiSuat", nullable = false, precision = 12, scale = 0)
	public float getLaiSuat() {
		return this.laiSuat;
	}

	public void setLaiSuat(float laiSuat) {
		this.laiSuat = laiSuat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaitietkiem")
	public Set<Sotietkiem> getSotietkiems() {
		return this.sotietkiems;
	}

	public void setSotietkiems(Set<Sotietkiem> sotietkiems) {
		this.sotietkiems = sotietkiems;
	}

}
