package model;
// Generated Mar 24, 2019 4:26:40 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaitaikhoan generated by hbm2java
 */
@Entity
@Table(name = "loaitaikhoan", catalog = "QLSTK")
public class Loaitaikhoan implements java.io.Serializable {

	private String maLoaiTaiKhoan;
	private String tenLoaiTaiKhoan;
	private Set<Taikhoankhachhang> taikhoankhachhangs = new HashSet<Taikhoankhachhang>(0);

	public Loaitaikhoan() {
	}

	public Loaitaikhoan(String maLoaiTaiKhoan, String tenLoaiTaiKhoan) {
		this.maLoaiTaiKhoan = maLoaiTaiKhoan;
		this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
	}

	public Loaitaikhoan(String maLoaiTaiKhoan, String tenLoaiTaiKhoan, Set<Taikhoankhachhang> taikhoankhachhangs) {
		this.maLoaiTaiKhoan = maLoaiTaiKhoan;
		this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
		this.taikhoankhachhangs = taikhoankhachhangs;
	}

	@Id

	@Column(name = "MaLoaiTaiKhoan", unique = true, nullable = false, length = 20)
	public String getMaLoaiTaiKhoan() {
		return this.maLoaiTaiKhoan;
	}

	public void setMaLoaiTaiKhoan(String maLoaiTaiKhoan) {
		this.maLoaiTaiKhoan = maLoaiTaiKhoan;
	}

	@Column(name = "TenLoaiTaiKhoan", nullable = false, length = 50)
	public String getTenLoaiTaiKhoan() {
		return this.tenLoaiTaiKhoan;
	}

	public void setTenLoaiTaiKhoan(String tenLoaiTaiKhoan) {
		this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaitaikhoan")
	public Set<Taikhoankhachhang> getTaikhoankhachhangs() {
		return this.taikhoankhachhangs;
	}

	public void setTaikhoankhachhangs(Set<Taikhoankhachhang> taikhoankhachhangs) {
		this.taikhoankhachhangs = taikhoankhachhangs;
	}

}
