package model;
// Generated Mar 24, 2019 4:26:40 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien", catalog = "QLSTK")
public class Nhanvien implements java.io.Serializable {

	private String maNhanVien;
	private String hoTen;
	private Date ngaySinh;
	private String gioiTinh;
	private String diaChi;
	private String cmnd;
	private String dienThoai;
	private String email;
	private Set<Dangnhap> dangnhaps = new HashSet<Dangnhap>(0);

	public Nhanvien() {
	}

	public Nhanvien(String maNhanVien, String hoTen, Date ngaySinh, String gioiTinh, String diaChi, String cmnd,
			String dienThoai, String email) {
		this.maNhanVien = maNhanVien;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.cmnd = cmnd;
		this.dienThoai = dienThoai;
		this.email = email;
	}

	public Nhanvien(String maNhanVien, String hoTen, Date ngaySinh, String gioiTinh, String diaChi, String cmnd,
			String dienThoai, String email, Set<Dangnhap> dangnhaps) {
		this.maNhanVien = maNhanVien;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.cmnd = cmnd;
		this.dienThoai = dienThoai;
		this.email = email;
		this.dangnhaps = dangnhaps;
	}

	@Id

	@Column(name = "MaNhanVien", unique = true, nullable = false, length = 20)
	public String getMaNhanVien() {
		return this.maNhanVien;
	}

	public void setMaNhanVien(String maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	@Column(name = "HoTen", nullable = false, length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", nullable = false, length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh", nullable = false, length = 10)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi", nullable = false)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "CMND", nullable = false, length = 20)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "DienThoai", nullable = false, length = 20)
	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Dangnhap> getDangnhaps() {
		return this.dangnhaps;
	}

	public void setDangnhaps(Set<Dangnhap> dangnhaps) {
		this.dangnhaps = dangnhaps;
	}

}
