package model;
// Generated Mar 24, 2019 4:26:40 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieuruttien generated by hbm2java
 */
@Entity
@Table(name = "phieuruttien", catalog = "QLSTK")
public class Phieuruttien implements java.io.Serializable {

	private String maPhieuRut;
	private Sotietkiem sotietkiem;
	private Date ngayRutTien;
	private BigDecimal soTienRut;

	public Phieuruttien() {
	}

	public Phieuruttien(String maPhieuRut, Sotietkiem sotietkiem, Date ngayRutTien, BigDecimal soTienRut) {
		this.maPhieuRut = maPhieuRut;
		this.sotietkiem = sotietkiem;
		this.ngayRutTien = ngayRutTien;
		this.soTienRut = soTienRut;
	}

	@Id

	@Column(name = "MaPhieuRut", unique = true, nullable = false, length = 20)
	public String getMaPhieuRut() {
		return this.maPhieuRut;
	}

	public void setMaPhieuRut(String maPhieuRut) {
		this.maPhieuRut = maPhieuRut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSoTietKiem", nullable = false)
	public Sotietkiem getSotietkiem() {
		return this.sotietkiem;
	}

	public void setSotietkiem(Sotietkiem sotietkiem) {
		this.sotietkiem = sotietkiem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayRutTien", nullable = false, length = 10)
	public Date getNgayRutTien() {
		return this.ngayRutTien;
	}

	public void setNgayRutTien(Date ngayRutTien) {
		this.ngayRutTien = ngayRutTien;
	}

	@Column(name = "SoTienRut", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSoTienRut() {
		return this.soTienRut;
	}

	public void setSoTienRut(BigDecimal soTienRut) {
		this.soTienRut = soTienRut;
	}

}
