package model;
// Generated Mar 24, 2019 4:26:40 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quydinh generated by hbm2java
 */
@Entity
@Table(name = "quydinh", catalog = "QLSTK")
public class Quydinh implements java.io.Serializable {

	private String maQd;
	private String tenQd;
	private String chiTiet;

	public Quydinh() {
	}

	public Quydinh(String maQd, String tenQd, String chiTiet) {
		this.maQd = maQd;
		this.tenQd = tenQd;
		this.chiTiet = chiTiet;
	}

	@Id

	@Column(name = "MaQD", unique = true, nullable = false, length = 20)
	public String getMaQD() {
		return this.maQd;
	}

	public void setMaD(String maQd) {
		this.maQd = maQd;
	}

	@Column(name = "TenQD", nullable = false, length = 255)
	public String getTenQD() {
		return this.tenQd;
	}

	public void setTenQD(String tenQd) {
		this.tenQd = tenQd;
	}

	@Column(name = "ChiTiet", nullable = false, length = 255)
	public String getChiTiet() {
		return this.chiTiet;
	}

	public void setChiTiet(String chiTiet) {
		this.chiTiet = chiTiet;
	}
}
